"""Generate and email a daily portfolio report.

Runs on a schedule (cron or APScheduler), pulls full cross-reference
data for each ticker in the portfolio, builds an HTML email with
key metrics and signals, and sends it via SMTP.
"""
import os
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from veroq import VeroqClient

# Configuration
PORTFOLIO = ["NVDA", "AAPL", "MSFT", "GOOGL", "AMZN"]
RECIPIENT = os.environ.get("REPORT_EMAIL", "team@example.com")
SMTP_HOST = os.environ.get("SMTP_HOST", "smtp.gmail.com")
SMTP_USER = os.environ.get("SMTP_USER", "")
SMTP_PASS = os.environ.get("SMTP_PASS", "")

client = VeroqClient()

def build_report() -> str:
    """Fetch data for each ticker and build an HTML report."""
    rows_html = ""
    for ticker in PORTFOLIO:
        # Full cross-reference: price, technicals, sentiment, news in one call
        result = client.ask(f"{ticker} full analysis")
        data = result.get("data", {}).get("ticker", {})
        price = data.get("price", {})
        signal = result.get("trade_signal", {})

        color = "#00CC66" if signal.get("score", 50) >= 60 else "#FF4444"
        rows_html += f"""
        <tr>
            <td><b>{ticker}</b></td>
            <td>${price.get('current', '?')}</td>
            <td>{price.get('change_pct', '?')}%</td>
            <td style="color:{color}">{signal.get('action', '?').upper()} ({signal.get('score', '?')})</td>
            <td>{result['confidence']['level']}</td>
        </tr>"""

    return f"""
    <html><body>
    <h2>Daily Portfolio Report - {datetime.now():%B %d, %Y}</h2>
    <table border="1" cellpadding="8" cellspacing="0">
        <tr><th>Ticker</th><th>Price</th><th>Change</th><th>Signal</th><th>Confidence</th></tr>
        {rows_html}
    </table>
    <p style="color:#888">Generated by VEROQ at {datetime.now():%H:%M UTC}</p>
    </body></html>"""

def send_email(html_body: str):
    """Send the report via SMTP."""
    msg = MIMEMultipart("alternative")
    msg["Subject"] = f"Portfolio Report - {datetime.now():%Y-%m-%d}"
    msg["From"] = SMTP_USER
    msg["To"] = RECIPIENT
    msg.attach(MIMEText(html_body, "html"))

    with smtplib.SMTP_SSL(SMTP_HOST, 465) as server:
        server.login(SMTP_USER, SMTP_PASS)
        server.sendmail(SMTP_USER, RECIPIENT, msg.as_string())
    print(f"Report sent to {RECIPIENT}")

# Generate and send
report = build_report()
send_email(report)
print(f"Daily report complete for {len(PORTFOLIO)} tickers")
